USE [master]

CREATE SERVER AUDIT [server.privileged.user.access.log]
TO SECURITY_LOG

CREATE SERVER AUDIT SPECIFICATION [server.privileged.user.access.specification]
FOR SERVER AUDIT [server.privileged.user.access.log]
ADD (AUDIT_CHANGE_GROUP),
ADD (LOGIN_CHANGE_PASSWORD_GROUP),
ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP),
ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (SERVER_PERMISSION_CHANGE_GROUP),
ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP)
WITH (STATE = ON)
